version: '2'

networks:
  prodnetwork:
    driver: bridge

services:

 gitlab:
  image: gitlab/gitlab-ce:latest
  restart: always
  hostname: 'gitlab'
  networks:
      - prodnetwork
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      # external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - "80:80"
    - "443:443"
    - "2222:22"
  volumes:
    - ./gitlab/config:/etc/gitlab
    - ./gitlab/logs:/var/log/gitlab
    - ./gitlab/data:/var/opt/gitlab
